export const ROUTE_PATHS = {
  HOME: '/',
  LOGIN: '/login',
  TEACHER: '/teacher',
  STUDENT: '/student',
  COURSE: '/course',
  FACILITY: '/facility',
  ATTENDANCE: '/attendance',
  CALENDAR: '/calendar',
  SCHEDULE: '/schedule',
  ACCOUNT: '/account',
  FINANCE: '/finance',
  REGISTER: '/course/register',
  DEFER: '/course/defer',
  REPORT: '/report',
  NOTICE: '/notice',
  REVIEW: '/review',
  SYSTEM_ERROR: '/system-error',
  LOGOUT: '/logout',
}
